name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: echo ${{ secrets.ACR_USERNAME }}
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: miranda.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build . -t miranda.azurecr.io/hotel-miranda-server:${{ github.sha }}
          docker push miranda.azurecr.io/hotel-miranda-server:${{ github.sha }}
